x-default: &default
  restart: unless-stopped
  volumes:
    - &localtime /etc/localtime:/etc/localtime:ro
    - &timezone /etc/timezone:/etc/timezone:ro
  logging:
    driver: json-file
    options:
      max-size: 1m

services:
  app:
    <<: *default
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-docker.io}/local/mcp-template-python:${BUILD_VERSION:-latest}
    ports:
      - "3001:${PORT:-3001}"
